In [1]:
import numpy as np
import pandas as pd
from supabase import create_client,Client
from dotenv import load_dotenv
import os
from datetime import datetime,timedelta

In [2]:
load_dotenv()
supabase_URL=os.getenv("NEXT_PUBLIC_SUPABASE_URL")
supabase_SERVICE_ROLE=os.getenv("SUPABASE_SERVICE_ROLE")
supabase=create_client(supabase_URL,supabase_SERVICE_ROLE)

In [3]:
historic_price=supabase.table("historic_price").select("*").limit(6000).execute()
df_historic_price=pd.DataFrame(historic_price.data)
df_historic_price['price']

0      5680
1      6244
2      7479
3      8633
4      5859
       ...
995    6195
996    6195
997    6195
998    6085
999    6195
Name: price, Length: 1000, dtype: int64

In [4]:
# here we drop id cos i dont think it does anything worthwile
df_historic_price=df_historic_price.drop('id',axis=1)
df_historic_price.head()

,route_id,airline_id,departure_date,price,created_at
0,1cbf0f58-1cba-46d8-8eec-f9c0ec5acd1f,df66ebda-424a-4644-92e9-8ff34e3be56d,2025-10-30,5680,2025-10-24T04:46:39.046096+00:00
1,1cbf0f58-1cba-46d8-8eec-f9c0ec5acd1f,4e9b1741-6fd4-47ef-ad87-3faff6bd6e40,2025-10-26,6244,2025-10-24T04:46:39.315211+00:00
2,1cbf0f58-1cba-46d8-8eec-f9c0ec5acd1f,df66ebda-424a-4644-92e9-8ff34e3be56d,2025-11-07,7479,2025-10-24T04:46:39.543931+00:00
3,1cbf0f58-1cba-46d8-8eec-f9c0ec5acd1f,df66ebda-424a-4644-92e9-8ff34e3be56d,2025-11-08,8633,2025-10-24T04:46:39.592916+00:00
4,1cbf0f58-1cba-46d8-8eec-f9c0ec5acd1f,ae06a7d9-3a3c-4886-bbb2-61c275650128,2025-10-24,5859,2025-10-24T04:47:18.779529+00:00

In [5]:
df_historic_price['created_at']=pd.to_datetime(df_historic_price["created_at"],utc=True)
# df_historic_price['created_at']=df_historic_price['created_at'].dt.strftime("%Y-%m-%d")
df_historic_price['departure_date']=pd.to_datetime(df_historic_price["departure_date"])

In [11]:
# lets pick only the rows for the past 30 days
today=datetime.today()
# endDate=pd.Timestamp(today-timedelta(days=30),tz='UTC')
endDate=pd.Timestamp("2025-10-13 00:56:45.063869+00:00")
df_historic_price_filtered = df_historic_price[df_historic_price['created_at'] > endDate]
df_historic_price_filtered

,route_id,airline_id,departure_date,price,created_at
0,1cbf0f58-1cba-46d8-8eec-f9c0ec5acd1f,df66ebda-424a-4644-92e9-8ff34e3be56d,2025-10-30,5680,2025-10-24 04:46:39.046096+00:00
1,1cbf0f58-1cba-46d8-8eec-f9c0ec5acd1f,4e9b1741-6fd4-47ef-ad87-3faff6bd6e40,2025-10-26,6244,2025-10-24 04:46:39.315211+00:00
2,1cbf0f58-1cba-46d8-8eec-f9c0ec5acd1f,df66ebda-424a-4644-92e9-8ff34e3be56d,2025-11-07,7479,2025-10-24 04:46:39.543931+00:00
3,1cbf0f58-1cba-46d8-8eec-f9c0ec5acd1f,df66ebda-424a-4644-92e9-8ff34e3be56d,2025-11-08,8633,2025-10-24 04:46:39.592916+00:00
4,1cbf0f58-1cba-46d8-8eec-f9c0ec5acd1f,ae06a7d9-3a3c-4886-bbb2-61c275650128,2025-10-24,5859,2025-10-24 04:47:18.779529+00:00
...,...,...,...,...,...
995,1c139a59-bff1-4269-b152-6e4003fbef79,ae06a7d9-3a3c-4886-bbb2-61c275650128,2025-11-16,6195,2025-10-24 05:27:13.615290+00:00
996,1c139a59-bff1-4269-b152-6e4003fbef79,ae06a7d9-3a3c-4886-bbb2-61c275650128,2025-11-18,6195,2025-10-24 05:27:13.679469+00:00
997,1c139a59-bff1-4269-b152-6e4003fbef79,ae06a7d9-3a3c-4886-bbb2-61c275650128,2025-11-20,6195,2025-10-24 05:27:13.741007+00:00
998,46f1d8d2-0c45-440a-8977-66111a872c6e,df66ebda-424a-4644-92e9-8ff34e3be56d,2025-11-13,6085,2025-10-24 05:27:13.784244+00:00
999,1c139a59-bff1-4269-b152-6e4003fbef79,ae06a7d9-3a3c-4886-bbb2-61c275650128,2025-11-23,6195,2025-10-24 05:27:13.850858+00:00